# Generated by Django 2.1 on 2018-08-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_id', models.TextField(blank=True)),
                ('img_url_set', models.TextField(blank=True)),
                ('img_url_date', models.TextField(blank=True)),
                ('img_url_num', models.IntegerField(default=0)),
            ],
        ),
    ]
